/**
 * CLI definition.
 *
 * Generated by ph-clint. Regions bracketed by @clint:begin/@clint:end
 * markers are rewritten by ph-clint when the project spec changes.
 * Everything outside the markers is user-editable and preserved.
 */
import path from 'node:path';
import { existsSync } from 'node:fs';
import { defineCli, buildDefaultReactor } from '@powerhousedao/ph-clint';
import { CLI_NAME, CLI_VERSION, CLI_ROOT } from './config.js';
import { configSchema, secretsSchema } from './framework.js';

// @clint:begin imports
import { documentModels } from '@powerhousedao/ph-lelantos-app';
import { createAgent } from './agents/agent.js';
// @clint:end imports

const appDir = path.resolve(CLI_ROOT, '../ph-lelantos-app');

function resolveConnectAssets(dir: string): string | undefined {
  const assetsDir = path.join(dir, 'dist', 'connect');
  return existsSync(path.join(assetsDir, 'index.html')) ? assetsDir : undefined;
}

export const cli = defineCli({
  name: CLI_NAME,
  version: CLI_VERSION,
  description: `${CLI_NAME} v${CLI_VERSION}`,
  configSchema,
  secretsSchema,

  // @clint:begin commands
  commands: [],
  // @clint:end commands

  // @clint:begin services
  services: [],
  // @clint:end services

  // @clint:begin triggers
  triggers: [],
  // @clint:end triggers

  // @clint:begin prompts
  prompts: {
    artifacts: [],
    agents: {},
    skills: {},
  },
  // @clint:end prompts

  // @clint:begin events
  events: {},
  // @clint:end events

  // @clint:begin interactive
  interactive: {
    welcome: ({ config, workdir }) =>
      [
        `${CLI_NAME} v${CLI_VERSION}`,
        `Workdir: ${workdir}`,
        `Switchboard: http://localhost:${config.switchboardPort}`,
        `Connect:     http://localhost:${config.connectPort}`,
        '',
        'Type a message to talk to the agent, or /help for commands.',
      ].join('\n'),
  },
  // @clint:end interactive
});

// @clint:begin reactor
cli.configureReactor({
  create: (ctx) =>
    buildDefaultReactor(ctx, {
      documentModels,
      drive: { name: 'ph-lelantos' },
    }),
  switchboard: { enabled: true },
  connect: { enabled: true, workdir: appDir, assetsDir: resolveConnectAssets(appDir) },
});
// @clint:end reactor

// @clint:begin mastra
cli.configureAgent(createAgent);
// @clint:end mastra
