/**
 * THIS FILE IS GENERATED BY ph-clint-cli. DO NOT EDIT.
 *
 * Regenerated on every `ph-clint clint-project-regen` and on every spec-change
 * tick. Put custom bindings in `framework.ts`, not here — edits to
 * this file will be overwritten.
 */
import { defineRegistry } from '@powerhousedao/ph-clint';

/**
 * Typed document registry derived from the reactor package's document models.
 * Regenerated whenever the spec's packages or document types change.
 */
export const registry = defineRegistry([] as const);

export type Registry = typeof registry;
